<cfscript>
/**
 * ========================================================================
 * API ENDPOINT: GEMINI DATA ANALYTICS AGENT PLATFORM PROXY
 * ========================================================================
 *
 * PURPOSE:     Proxies chat requests from the React frontend to the
 * Google Cloud Gemini Data Analytics Agent chat API.
 * Handles authentication and conversation resource management on the server side.
 *
 * ========================================================================
 */

// --- HELPER: Get secure Google Cloud token ---
function getAuthToken() {
    try {
        var httpRes = "";
        cfhttp(url="http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token", method="GET", result="httpRes") {
            cfhttpparam(type="header", name="Metadata-Flavor", value="Google");
        }
        if (val(httpRes.statusCode) != 200) throw(message="Metadata token failed", detail=httpRes.fileContent);
        return deserializeJson(httpRes.fileContent).access_token;
    } catch (any e) {
        throw(message="Could not get auth token.", detail=e.message);
    }
}

    response = { "success": false, "text": "", "error": "" };

    try {
        // 1. Setup Variables
        projectId  = server.system.environment.GOOGLE_CLOUD_PROJECT;
        agentId    = server.system.environment.ALLOYDB_CA_DATA_AGENT_ID ?: server.system.environment.VERTEX_AGENT_ID ?: "";
        
        if (left(agentId, 6) != "agent_") {
            agentId = "agent_" & agentId;
        }
        agentPath = "projects/#projectId#/locations/global/dataAgents/#agentId#";

        // 2. Parse Request
        requestBody = deserializeJson(toString(getHttpRequestData().content));
        if (!structKeyExists(requestBody, "prompt")) throw("Missing 'prompt' in request");
        
        userPrompt = requestBody.prompt;
        authToken = getAuthToken();
        
        // Client-side UUID generated by the React frontend
        clientSessionId = structKeyExists(requestBody, "sessionId") ? requestBody.sessionId : "";
        conversationPath = "";

        // 3. Resolve conversation path via application scope mapping
        if (len(clientSessionId) > 0) {
            if (!structKeyExists(application, "dataAgentConversations")) {
                lock scope="Application" type="exclusive" timeout=5 {
                    if (!structKeyExists(application, "dataAgentConversations")) {
                        application.dataAgentConversations = {};
                    }
                }
            }
            if (structKeyExists(application.dataAgentConversations, clientSessionId)) {
                conversationPath = application.dataAgentConversations[clientSessionId];
            }
        }

        // 4. Step 1: Create Conversation if it hasn't been created/mapped yet
        if (len(conversationPath) == 0) {
            createUrl = "https://geminidataanalytics.googleapis.com/v1beta/projects/#projectId#/locations/global/conversations";
            createBody = { "agents": [ agentPath ] };
            
            createRes = "";
            cfhttp(url=createUrl, method="POST", result="createRes", timeout=15) {
                cfhttpparam(type="header", name="Authorization", value="Bearer #authToken#");
                cfhttpparam(type="header", name="Content-Type", value="application/json");
                cfhttpparam(type="body", value=serializeJson(createBody));
            }
            
            if (val(createRes.statusCode) != 200 && val(createRes.statusCode) != 201) {
                throw(message="Google Conversation Creation Error: #createRes.statusCode#", detail=createRes.fileContent);
            }
            
            convData = deserializeJson(createRes.fileContent);
            conversationPath = convData.name;

            // Map the clientSessionId to the resulting GCP conversationPath
            if (len(clientSessionId) > 0) {
                lock scope="Application" type="exclusive" timeout=5 {
                    application.dataAgentConversations[clientSessionId] = conversationPath;
                }
            }
        }

        // 5. Step 2: Send Chat Turn using the resolved conversationPath
        chatUrl = "https://geminidataanalytics.googleapis.com/v1beta/projects/#projectId#/locations/global:chat";
        
        chatBody = {
            "parent": "projects/#projectId#/locations/global",
            "client_id": "ALLOYDB",
            "conversation_reference": {
                "conversation": conversationPath,
                "data_agent_context": {
                    "data_agent": agentPath
                }
            },
            "messages": [
                {
                    "user_message": {
                        "text": userPrompt
                    }
                }
            ]
        };

        cfhttp(url=chatUrl, method="POST", result="apiRes", timeout=45) {
            cfhttpparam(type="header", name="Authorization", value="Bearer #authToken#");
            cfhttpparam(type="header", name="Content-Type", value="application/json");
            cfhttpparam(type="body", value=serializeJson(chatBody));
        }

        // 6. Parse Response
        if (val(apiRes.statusCode) != 200) {
            throw(message="Google Chat Error: #apiRes.statusCode#", detail=apiRes.fileContent);
        }

        googleData = deserializeJson(apiRes.fileContent);

        // Find the FINAL_RESPONSE event in the JSON array of events returned by :chat
        botReply = "No response from data agent.";
        for (event in googleData) {
            if (structKeyExists(event, "systemMessage") 
                && structKeyExists(event.systemMessage, "text") 
                && structKeyExists(event.systemMessage.text, "textType") 
                && event.systemMessage.text.textType == "FINAL_RESPONSE"
                && arrayLen(event.systemMessage.text.parts) > 0) {
                
                botReply = event.systemMessage.text.parts[1];
                break;
            }
        }

        response.success = true;
        response.text = botReply;
        response.sessionId = clientSessionId; // Return back clientSessionId to maintain frontend mapping

    } catch (any e) {
        cfheader(statusCode=500);
        response.error = e.message;
        response.detail = e.detail;
    }

    writeOutput(serializeJson(response));
</cfscript>